import { PublicLayout } from '@/components/layout/PublicLayout';
import { Link } from 'react-router-dom';
import PageMeta from '@/components/seo/PageMeta';
import { useContentLang } from '@/context/LanguageContext';

const _t = {
  en: {
    pageTitle: 'About Syrabit.ai',
    pageDescription: 'Syrabit.ai is the AI-powered educational browser for AHSEC, SEBA and Degree students in Assam. Learn about our mission, platform architecture, and how we help students succeed.',
    pageSubtitle: 'The Educational Browser for Assam Board Students',
    missionTitle: 'Our Mission',
    missionP: 'Syrabit.ai is an AI-powered educational platform designed to deliver syllabus-aligned, reliable, and context-aware learning for students. Built specifically for students of Assam — covering AHSEC (Class 11–12), SEBA, and Degree (B.Com, B.A, B.Sc) syllabi — we provide structured study notes, previous year questions, MCQs, important questions, and an AI tutor that answers only within your syllabus.',
    offerTitle: 'What We Offer',
    offerItems: [
      'Chapter-wise notes aligned to official AHSEC and Degree syllabi',
      'Previous Year Questions (PYQs) with solutions',
      'MCQs and important questions for exam preparation',
      'AI tutor (Syra) that stays within your syllabus — no hallucination, no off-topic answers',
      'Support for multiple subjects across Science, Commerce, and Arts streams',
    ],
    archTitle: 'Platform Architecture',
    archP: 'The platform organizes academic content into structured subject cards that function as dedicated knowledge hubs, enabling intuitive browsing and learning. By combining structured content navigation with intelligent AI assistance, Syrabit.ai transforms traditional studying into an interactive, guided, and verifiable learning experience tailored to board-specific education systems.',
    hierTitle: 'Hierarchical Knowledge Mapping',
    hierP1: 'The system follows a hierarchical knowledge mapping structure where every query is contextually linked from',
    hierLabels: ['Topic', 'Chapter', 'Subject', 'Course', 'Board'],
    hierP2: '. This ensures that all responses generated by Syrabit.ai are syllabus-aligned and academically accurate. Additionally, each answer includes dedicated source citations, allowing users to trace the exact origin of the information for transparency and reliability.',
    browserTitle: 'The Browser — Subject Cards as Knowledge Hubs',
    browserP: 'The Browser page serves as an organized learning interface where each subject is presented as an interactive card functioning like a mini subject-specific knowledge hub. These subject cards act as structured data sources that power the Syrabit.ai chat, enabling context-aware, syllabus-aligned responses based on selected topics.',
    chatTitle: 'AI Chat with Source Citations',
    chatP: 'The integrated AI chat leverages these structured data sources to provide accurate, personalized answers, each supported by clear source citations for transparency and trust. Unlike generic chatbots, Syra uses a multi-stage retrieval pipeline specifically designed to keep answers grounded in your actual chapter content. If Syra cannot find relevant material with high confidence, it explicitly tells you rather than making something up.',
    serveTitle: 'Who We Serve',
    serveP: 'We serve students across Assam preparing for board exams and university exams under AHSEC, SEBA, Gauhati University, and Dibrugarh University curricula. Our content covers Class 11, Class 12, and undergraduate degree programmes.',
    builtTitle: 'Built With',
    builtP: 'Syrabit.ai is a production-grade platform built with React 18, FastAPI, and a multi-provider LLM pipeline (Groq, Cerebras, Sarvam AI, Gemini) — powered by MongoDB Atlas, Redis, Cloudflare Workers, and a custom programmatic SEO engine that auto-generates 15,000+ optimized pages. The entire system is deployed as a hybrid architecture across Cloudflare\u2019s edge network and Railway.',
    techLink: 'View the full technology stack and architecture details →',
    contactTitle: 'Contact',
    contactP: 'For questions, feedback, or partnerships, reach us at',
  },
  as: {
    pageTitle: 'Syrabit.ai ৰ বিষয়ে',
    pageDescription: 'Syrabit.ai হৈছে অসমৰ AHSEC, SEBA আৰু ডিগ্ৰী ছাত্ৰ-ছাত্ৰীৰ বাবে AI-চালিত শিক্ষামূলক ব্ৰাউজাৰ। আমাৰ লক্ষ্য, মঞ্চৰ আৰ্কিটেকচাৰ, আৰু আমি কেনেকৈ ছাত্ৰ-ছাত্ৰীক সফল হোৱাত সহায় কৰোঁ সেই বিষয়ে জানক।',
    pageSubtitle: 'অসম বৰ্ডৰ ছাত্ৰ-ছাত্ৰীৰ বাবে শিক্ষামূলক ব্ৰাউজাৰ',
    missionTitle: 'আমাৰ লক্ষ্য',
    missionP: 'Syrabit.ai হৈছে পাঠ্যক্ৰম-সংযুক্ত, নিৰ্ভৰযোগ্য, আৰু প্ৰসংগ-সচেতন শিক্ষণ প্ৰদান কৰিবলৈ ডিজাইন কৰা এখন AI-চালিত শিক্ষামূলক মঞ্চ। বিশেষভাৱে অসমৰ ছাত্ৰ-ছাত্ৰীৰ বাবে নিৰ্মিত — AHSEC (শ্ৰেণী 11–12), SEBA, আৰু ডিগ্ৰী (B.Com, B.A, B.Sc) পাঠ্যক্ৰম সামৰি — আমি গাঁথনিগত অধ্যয়ন টোকা, আগৰ বছৰৰ প্ৰশ্ন, MCQ, গুৰুত্বপূৰ্ণ প্ৰশ্ন, আৰু কেৱল আপোনাৰ পাঠ্যক্ৰমৰ ভিতৰতে উত্তৰ দিয়া এটা AI শিক্ষক প্ৰদান কৰোঁ।',
    offerTitle: 'আমি কি আগবঢ়াওঁ',
    offerItems: [
      'চৰকাৰী AHSEC আৰু ডিগ্ৰী পাঠ্যক্ৰমৰ সৈতে সংযুক্ত অধ্যায়ভিত্তিক টোকা',
      'সমাধানসহ আগৰ বছৰৰ প্ৰশ্ন (PYQ)',
      'পৰীক্ষাৰ প্ৰস্তুতিৰ বাবে MCQ আৰু গুৰুত্বপূৰ্ণ প্ৰশ্ন',
      'AI শিক্ষক (Syra) যিয়ে আপোনাৰ পাঠ্যক্ৰমৰ ভিতৰতে থাকে — কোনো হেলুচিনেচন নাই, কোনো বিষয়ৰ বাহিৰৰ উত্তৰ নাই',
      'বিজ্ঞান, বাণিজ্য, আৰু কলা শাখাৰ একাধিক বিষয়ৰ সমৰ্থন',
    ],
    archTitle: 'মঞ্চৰ আৰ্কিটেকচাৰ',
    archP: 'মঞ্চখনে শৈক্ষিক বিষয়বস্তুক গাঁথনিগত বিষয় কাৰ্ডত সংগঠিত কৰে যিবোৰে নিবেদিত জ্ঞান কেন্দ্ৰ হিচাপে কাম কৰে, স্বজ্ঞাত ব্ৰাউজিং আৰু শিক্ষণ সক্ষম কৰে। গাঁথনিগত বিষয়বস্তু নেভিগেচন আৰু বুদ্ধিমান AI সহায়তা সংযুক্ত কৰি, Syrabit.ai য়ে পৰম্পৰাগত অধ্যয়নক বৰ্ড-নিৰ্দিষ্ট শিক্ষা ব্যৱস্থাৰ বাবে উপযুক্ত এটা ইণ্টাৰেক্টিভ, পথ-নিৰ্দেশিত, আৰু পৰীক্ষণযোগ্য শিক্ষণ অভিজ্ঞতালৈ ৰূপান্তৰিত কৰে।',
    hierTitle: 'হায়াৰাৰ্কিকেল জ্ঞান মেপিং',
    hierP1: 'ব্যৱস্থাটোৱে এটা হায়াৰাৰ্কিকেল জ্ঞান মেপিং গঠন অনুসৰণ কৰে য\'ত প্ৰতিটো প্ৰশ্ন প্ৰসংগভিত্তিকভাৱে সংযুক্ত হয়',
    hierLabels: ['বিষয়বস্তু', 'অধ্যায়', 'বিষয়', 'পাঠ্যক্ৰম', 'বৰ্ড'],
    hierP2: '। ই নিশ্চিত কৰে যে Syrabit.ai ৰ দ্বাৰা সৃষ্টি কৰা সকলো উত্তৰ পাঠ্যক্ৰম-সংযুক্ত আৰু শৈক্ষিকভাৱে সঠিক। ইয়াৰ উপৰিও, প্ৰতিটো উত্তৰত নিবেদিত উৎস উদ্ধৃতি অন্তৰ্ভুক্ত থাকে, যাৰ ফলত ব্যৱহাৰকাৰীসকলে স্বচ্ছতা আৰু নিৰ্ভৰযোগ্যতাৰ বাবে তথ্যৰ সঠিক উৎস অনুসৰণ কৰিব পাৰে।',
    browserTitle: 'ব্ৰাউজাৰ — জ্ঞান কেন্দ্ৰ হিচাপে বিষয় কাৰ্ড',
    browserP: 'ব্ৰাউজাৰ পৃষ্ঠাখনে এখন সংগঠিত শিক্ষণ ইণ্টাৰফেচ হিচাপে কাম কৰে য\'ত প্ৰতিটো বিষয়ক এটা ক্ষুদ্ৰ বিষয়-নিৰ্দিষ্ট জ্ঞান কেন্দ্ৰৰ দৰে কাম কৰা ইণ্টাৰেক্টিভ কাৰ্ড হিচাপে উপস্থাপন কৰা হয়। এই বিষয় কাৰ্ডবোৰে গাঁথনিগত তথ্য উৎস হিচাপে কাম কৰে যিয়ে Syrabit.ai চেটক শক্তি প্ৰদান কৰে, নিৰ্বাচিত বিষয়বস্তুৰ ওপৰত ভিত্তি কৰি প্ৰসংগ-সচেতন, পাঠ্যক্ৰম-সংযুক্ত উত্তৰ সক্ষম কৰে।',
    chatTitle: 'উৎস উদ্ধৃতিৰ সৈতে AI চেট',
    chatP: 'সংহত AI চেটে এই গাঁথনিগত তথ্য উৎসসমূহ ব্যৱহাৰ কৰি সঠিক, ব্যক্তিগতকৃত উত্তৰ প্ৰদান কৰে, প্ৰতিটো স্বচ্ছতা আৰু বিশ্বাসৰ বাবে স্পষ্ট উৎস উদ্ধৃতিৰে সমৰ্থিত। সাধাৰণ চেটবটৰ দৰে নহয়, Syra ই আপোনাৰ প্ৰকৃত অধ্যায়ৰ বিষয়বস্তুত উত্তৰ ভিত্তিক ৰাখিবলৈ বিশেষভাৱে ডিজাইন কৰা বহু-পৰ্যায়ৰ ৰিট্ৰিভেল পাইপলাইন ব্যৱহাৰ কৰে। যদি Syra ই উচ্চ আত্মবিশ্বাসেৰে প্ৰাসংগিক সামগ্ৰী বিচাৰি নাপায়, তেন্তে ই কিবা এটা সাজি উলিওৱাৰ পৰিৱৰ্তে স্পষ্টভাৱে আপোনাক জনায়।',
    serveTitle: 'আমি কাক সেৱা কৰোঁ',
    serveP: 'আমি AHSEC, SEBA, গুৱাহাটী বিশ্ববিদ্যালয়, আৰু ডিব্ৰুগড় বিশ্ববিদ্যালয়ৰ পাঠ্যক্ৰমৰ অধীনত বৰ্ড পৰীক্ষা আৰু বিশ্ববিদ্যালয় পৰীক্ষাৰ বাবে প্ৰস্তুতি লোৱা সমগ্ৰ অসমৰ ছাত্ৰ-ছাত্ৰীক সেৱা কৰোঁ। আমাৰ বিষয়বস্তুত শ্ৰেণী 11, শ্ৰেণী 12, আৰু স্নাতক ডিগ্ৰী কাৰ্যক্ৰম সামৰি লোৱা হৈছে।',
    builtTitle: 'কিহেৰে নিৰ্মিত',
    builtP: 'Syrabit.ai হৈছে React 18, FastAPI, আৰু মাল্টি-প্ৰভাইডাৰ LLM পাইপলাইন (Groq, Cerebras, Sarvam AI, Gemini) ৰ সৈতে নিৰ্মিত এখন প্ৰডাকচন-গ্ৰেড মঞ্চ — MongoDB Atlas, Redis, Cloudflare Workers, আৰু 15,000+ অনুকূলিত পৃষ্ঠা স্বয়ংক্ৰিয়ভাৱে সৃষ্টি কৰা এটা কাষ্টম প্ৰগ্ৰামেটিক SEO ইঞ্জিনৰ দ্বাৰা চালিত। সমগ্ৰ ব্যৱস্থাটো Cloudflare ৰ এজ নেটৱৰ্ক আৰু Railway ৰ মাজত হাইব্ৰিড আৰ্কিটেকচাৰ হিচাপে মোতায়েন কৰা হৈছে।',
    techLink: 'সম্পূৰ্ণ প্ৰযুক্তি স্তৰ আৰু আৰ্কিটেকচাৰৰ বিৱৰণ চাওক →',
    contactTitle: 'যোগাযোগ',
    contactP: 'প্ৰশ্ন, মতামত, বা অংশীদাৰিত্বৰ বাবে আমাৰ সৈতে যোগাযোগ কৰক',
  },
};

function getJsonLd(lang) {
  return {
    '@context': 'https://schema.org',
    '@type': 'AboutPage',
    name: lang === 'as' ? 'Syrabit.ai ৰ বিষয়ে' : 'About Syrabit.ai',
    url: 'https://syrabit.ai/about',
    inLanguage: lang === 'as' ? ['as', 'en'] : ['en', 'as'],
    description: lang === 'as'
      ? 'Syrabit.ai হৈছে অসমৰ AHSEC, SEBA আৰু ডিগ্ৰী ছাত্ৰ-ছাত্ৰীৰ বাবে AI-চালিত শিক্ষামূলক ব্ৰাউজাৰ।'
      : 'Syrabit.ai is the AI-powered educational browser for AHSEC, SEBA and Degree students in Assam.',
    isPartOf: {
      '@type': 'WebSite',
      name: 'Syrabit.ai',
      url: 'https://syrabit.ai',
    },
    publisher: {
      '@type': 'Organization',
      name: 'Syrabit',
      url: 'https://syrabit.ai',
      foundingDate: '2024',
      areaServed: {
        '@type': 'State',
        name: 'Assam',
        containedInPlace: { '@type': 'Country', name: 'India' },
      },
    },
  };
}

function LangToggle({ contentLang, switchLang }) {
  return (
    <div className="flex items-center gap-1 shrink-0 rounded-xl p-0.5" style={{ background: 'rgba(139,92,246,0.08)', border: '1px solid rgba(139,92,246,0.12)' }}>
      <button
        onClick={() => switchLang('en')}
        className={`h-9 px-3 rounded-lg text-xs font-semibold transition-all flex items-center gap-1.5 ${
          contentLang === 'en'
            ? 'text-white bg-violet-600 shadow-sm'
            : 'text-violet-600 hover:bg-violet-50'
        }`}
      >
        English
      </button>
      <button
        onClick={() => switchLang('as')}
        className={`h-9 px-3 rounded-lg text-xs font-semibold transition-all flex items-center gap-1.5 ${
          contentLang === 'as'
            ? 'text-white bg-violet-600 shadow-sm'
            : 'text-violet-600 hover:bg-violet-50'
        }`}
      >
        অসমীয়া
      </button>
    </div>
  );
}

export default function AboutPage() {
  const { contentLang, switchLang } = useContentLang();
  const t = _t[contentLang] || _t.en;
  const jsonLd = getJsonLd(contentLang);

  return (
    <PublicLayout>
      <PageMeta
        title={t.pageTitle}
        description={t.pageDescription}
        url="https://syrabit.ai/about"
        keywords="Syrabit.ai about, AI education platform Assam, AHSEC SEBA Degree, Syrabit ৰ বিষয়ে, অসমীয়া AI শিক্ষা মঞ্চ"
        jsonLd={[jsonLd]}
      />
      <div className="min-h-screen pt-8 pb-24 px-4">
        <div className="max-w-3xl mx-auto">
          <div className="flex items-start justify-between gap-4 mb-2">
            <h1 className="text-3xl font-semibold text-foreground">{t.pageTitle}</h1>
            <LangToggle contentLang={contentLang} switchLang={switchLang} />
          </div>
          <p className="text-muted-foreground text-sm mb-10">{t.pageSubtitle}</p>

          <div className="space-y-10 text-foreground/70 leading-relaxed">

            <div>
              <h2 className="text-foreground font-semibold mb-2">{t.missionTitle}</h2>
              <p>{t.missionP}</p>
            </div>

            <div>
              <h2 className="text-foreground font-semibold mb-2">{t.offerTitle}</h2>
              <ul className="list-disc list-inside space-y-2">
                {t.offerItems.map((item, i) => (
                  <li key={i}>{item}</li>
                ))}
              </ul>
            </div>

            <div>
              <h2 className="text-foreground font-semibold text-lg mb-3">{t.archTitle}</h2>
              <p className="mb-4">{t.archP}</p>
            </div>

            <div>
              <h2 className="text-foreground font-semibold text-lg mb-3">{t.hierTitle}</h2>
              <p>
                {t.hierP1}{' '}
                {t.hierLabels.map((label, i) => (
                  <span key={i}>
                    <span className="text-violet-600">{label}</span>
                    {i < t.hierLabels.length - 1 ? ' → ' : ''}
                  </span>
                ))}
                {t.hierP2}
              </p>
            </div>

            <div>
              <h2 className="text-foreground font-semibold text-lg mb-3">{t.browserTitle}</h2>
              <p>{t.browserP}</p>
            </div>

            <div>
              <h2 className="text-foreground font-semibold text-lg mb-3">{t.chatTitle}</h2>
              <p>{t.chatP}</p>
            </div>

            <div>
              <h2 className="text-foreground font-semibold mb-2">{t.serveTitle}</h2>
              <p>{t.serveP}</p>
            </div>

            <div>
              <h2 className="text-foreground font-semibold text-lg mb-3">{t.builtTitle}</h2>
              <p className="mb-3">{t.builtP}</p>
              <p>
                <Link to="/technology" className="text-violet-600 hover:underline">
                  {t.techLink}
                </Link>
              </p>
            </div>

            <div>
              <h2 className="text-foreground font-semibold mb-2">{t.contactTitle}</h2>
              <p>
                {t.contactP}{' '}
                <a href="mailto:admin@syrabit.ai" className="text-violet-600 hover:underline">
                  admin@syrabit.ai
                </a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </PublicLayout>
  );
}
