import { PublicLayout } from '@/components/layout/PublicLayout';
import { Link } from 'react-router-dom';
import PageMeta from '@/components/seo/PageMeta';

export default function AboutPage() {
  return (
    <PublicLayout>
      <PageMeta
        title="About Syrabit.ai"
        description="Syrabit.ai is the AI-powered educational browser for AHSEC, SEBA and Degree students in Assam. Learn about our mission, platform architecture, and how we help students succeed."
        url="https://syrabit.ai/about"
      />
      <div className="min-h-screen pt-8 pb-24 px-4">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-3xl font-semibold text-foreground mb-2">About Syrabit.ai</h1>
          <p className="text-muted-foreground text-sm mb-10">The Educational Browser for Assam Board Students</p>

          <div className="space-y-10 text-foreground/70 leading-relaxed">

            <div>
              <h2 className="text-foreground font-semibold mb-2">Our Mission</h2>
              <p>
                Syrabit.ai is an AI-powered educational platform designed to deliver syllabus-aligned,
                reliable, and context-aware learning for students. Built specifically for students of
                Assam — covering AHSEC (Class 11–12), SEBA, and Degree (B.Com, B.A, B.Sc) syllabi —
                we provide structured study notes, previous year questions, MCQs, important questions,
                and an AI tutor that answers only within your syllabus.
              </p>
            </div>

            <div>
              <h2 className="text-foreground font-semibold mb-2">What We Offer</h2>
              <ul className="list-disc list-inside space-y-2">
                <li>Chapter-wise notes aligned to official AHSEC and Degree syllabi</li>
                <li>Previous Year Questions (PYQs) with solutions</li>
                <li>MCQs and important questions for exam preparation</li>
                <li>AI tutor (Syra) that stays within your syllabus — no hallucination, no off-topic answers</li>
                <li>Support for multiple subjects across Science, Commerce, and Arts streams</li>
              </ul>
            </div>

            <div>
              <h2 className="text-foreground font-semibold text-lg mb-3">Platform Architecture</h2>
              <p className="mb-4">
                The platform organizes academic content into structured subject cards that function
                as dedicated knowledge hubs, enabling intuitive browsing and learning. By combining
                structured content navigation with intelligent AI assistance, Syrabit.ai transforms
                traditional studying into an interactive, guided, and verifiable learning experience
                tailored to board-specific education systems.
              </p>
            </div>

            <div>
              <h2 className="text-foreground font-semibold text-lg mb-3">Hierarchical Knowledge Mapping</h2>
              <p>
                The system follows a hierarchical knowledge mapping structure where every query is
                contextually linked from <span className="text-violet-600">Topic</span> →{' '}
                <span className="text-violet-600">Chapter</span> →{' '}
                <span className="text-violet-600">Subject</span> →{' '}
                <span className="text-violet-600">Course</span> →{' '}
                <span className="text-violet-600">Board</span>. This ensures that all responses
                generated by Syrabit.ai are syllabus-aligned and academically accurate. Additionally,
                each answer includes dedicated source citations, allowing users to trace the exact
                origin of the information for transparency and reliability.
              </p>
            </div>

            <div>
              <h2 className="text-foreground font-semibold text-lg mb-3">The Browser — Subject Cards as Knowledge Hubs</h2>
              <p>
                The Browser page serves as an organized learning interface where each subject is
                presented as an interactive card functioning like a mini subject-specific knowledge hub.
                These subject cards act as structured data sources that power the Syrabit.ai chat,
                enabling context-aware, syllabus-aligned responses based on selected topics.
              </p>
            </div>

            <div>
              <h2 className="text-foreground font-semibold text-lg mb-3">AI Chat with Source Citations</h2>
              <p>
                The integrated AI chat leverages these structured data sources to provide accurate,
                personalized answers, each supported by clear source citations for transparency and
                trust. Unlike generic chatbots, Syra uses a multi-stage retrieval pipeline specifically
                designed to keep answers grounded in your actual chapter content. If Syra cannot find
                relevant material with high confidence, it explicitly tells you rather than making
                something up.
              </p>
            </div>

            <div>
              <h2 className="text-foreground font-semibold mb-2">Who We Serve</h2>
              <p>
                We serve students across Assam preparing for board exams and university exams under
                AHSEC, SEBA, Gauhati University, and Dibrugarh University curricula. Our content covers
                Class 11, Class 12, and undergraduate degree programmes.
              </p>
            </div>

            <div>
              <h2 className="text-foreground font-semibold text-lg mb-3">Built With</h2>
              <p className="mb-3">
                Syrabit.ai is a production-grade platform built with React 18, FastAPI, and a
                multi-provider LLM pipeline (Groq, Cerebras, Sarvam AI, Gemini) — powered by
                MongoDB Atlas, Redis, Cloudflare Workers, and a custom programmatic SEO engine
                that auto-generates 15,000+ optimized pages. The entire system is deployed as a
                hybrid architecture across Cloudflare&apos;s edge network and Railway.
              </p>
              <p>
                <Link to="/technology" className="text-violet-600 hover:underline">
                  View the full technology stack and architecture details →
                </Link>
              </p>
            </div>

            <div>
              <h2 className="text-foreground font-semibold mb-2">Contact</h2>
              <p>
                For questions, feedback, or partnerships, reach us at{' '}
                <a href="mailto:admin@syrabit.ai" className="text-violet-600 hover:underline">
                  admin@syrabit.ai
                </a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </PublicLayout>
  );
}
