name = "syrabit-email"
main = "src/index.ts"
account_id = "d66e40eac539fff1db270fddf384a5ec"
compatibility_date = "2025-05-01"
compatibility_flags = ["nodejs_compat_v2"]

[placement]
mode = "smart"

logpush = true

[observability]
enabled = true
head_sampling_rate = 0.1

send_email = [
  { name = "EMAIL_SENDER" }
]

[[rules]]
type = "ESModule"
globs = ["**/*.ts"]
