name = "syrabit-email"
main = "src/index.ts"
account_id = "d66e40eac539fff1db270fddf384a5ec"
compatibility_date = "2025-05-01"

send_email = [
  { name = "EMAIL_SENDER" }
]

routes = [
  { pattern = "syrabit.ai/email/*", zone_name = "syrabit.ai" },
]

[placement]
mode = "smart"

[observability]
enabled = true
head_sampling_rate = 0.1
