#!/bin/bash

# ==============================================================================
# CLOUDFLARE & BACKEND WIRING EXECUTION SCRIPT
# ==============================================================================
# This script wires Cloudflare Workers, Pages, and Backend with pydantic-settings
# ==============================================================================

set -e

echo "🔐 Starting Cloudflare & Backend Wiring..."

# ------------------------------------------------------------------------------
# STEP 1: GENERATE SECRETS
# ------------------------------------------------------------------------------
echo "🎲 Generating cryptographically secure secrets..."

AI_FALLBACK_SECRET=$(openssl rand -hex 32)
AI_FALLBACK_SECRET_PROD=$(openssl rand -hex 32)
BACKEND_ORIGIN_SECRET=$(openssl rand -hex 32)
D1_SYNC_SECRET=$(openssl rand -hex 32)

echo "✅ Secrets generated successfully."

# ------------------------------------------------------------------------------
# STEP 2: IDENTIFY WORKER SUBDOMAIN
# ------------------------------------------------------------------------------
echo ""
echo "🌐 Identifying Cloudflare Workers Subdomain..."

WORKER_NAME=""
if [ -f "workers/edge-proxy/wrangler.toml" ]; then
    WORKER_NAME=$(grep "^name = " workers/edge-proxy/wrangler.toml | cut -d'"' -f2)
fi

if [ -z "$WORKER_NAME" ]; then
    echo "⚠️  Could not auto-detect worker name from wrangler.toml."
    read -p "Enter your Worker Name (e.g., 'syrabit-edge'): " WORKER_NAME
fi

CF_WORKERS_SUBDOMAIN="${WORKER_NAME}"
echo "📡 Target Worker Subdomain: ${CF_WORKERS_SUBDOMAIN}.workers.dev"

# ------------------------------------------------------------------------------
# STEP 3: UPDATE LOCAL DEVELOPMENT FILES
# ------------------------------------------------------------------------------
echo ""
echo "📝 Updating local development configuration..."

DEV_VARS_FILE="workers/edge-proxy/.dev.vars"
mkdir -p "$(dirname "$DEV_VARS_FILE")"

cat > "$DEV_VARS_FILE" <<EOF
# Auto-generated by wiring script
BACKEND_URL=http://localhost:8000
D1_SYNC_SECRET=${D1_SYNC_SECRET}
BACKEND_ORIGIN_SECRET=${BACKEND_ORIGIN_SECRET}
EDGE_AI_FALLBACK_SECRET=${AI_FALLBACK_SECRET}
SYNTHETIC_PROBE_CF_ACCESS_CLIENT_SECRET=local-dev-secret
EOF

echo "✅ Updated ${DEV_VARS_FILE}"

# ------------------------------------------------------------------------------
# STEP 4: DEPLOY SECRETS TO CLOUDFLARE WORKERS
# ------------------------------------------------------------------------------
echo ""
echo "☁️  Pushing secrets to Cloudflare Workers (Production)..."
echo "⚠️  Ensure you are logged in: wrangler login"

cd workers/edge-proxy

put_secret() {
    local NAME=$1
    local VALUE=$2
    local ENV_FLAG=$3
    
    if [ -n "$ENV_FLAG" ]; then
        echo "   Setting ${NAME} (--env ${ENV_FLAG})..."
        echo "${VALUE}" | wrangler secret put "${NAME}" --env "${ENV_FLAG}"
    else
        echo "   Setting ${NAME}..."
        echo "${VALUE}" | wrangler secret put "${NAME}"
    fi
}

# Production Secrets
put_secret "D1_SYNC_SECRET" "${D1_SYNC_SECRET}"
put_secret "BACKEND_ORIGIN_SECRET" "${BACKEND_ORIGIN_SECRET}"
put_secret "EDGE_AI_FALLBACK_SECRET" "${AI_FALLBACK_SECRET}"

echo ""
echo "☁️  Pushing secrets to Cloudflare Workers (Preview)..."
put_secret "D1_SYNC_SECRET" "${D1_SYNC_SECRET}" "preview"
put_secret "BACKEND_ORIGIN_SECRET" "${BACKEND_ORIGIN_SECRET}" "preview"
put_secret "EDGE_AI_FALLBACK_SECRET" "${AI_FALLBACK_SECRET}" "preview"

cd ../..

# ------------------------------------------------------------------------------
# STEP 5: OUTPUT BACKEND CONFIGURATION
# ------------------------------------------------------------------------------
echo ""
echo "=============================================================================="
echo "🎉 WIRING COMPLETE!"
echo "=============================================================================="
echo ""
echo "📋 COPY THE FOLLOWING TO YOUR GOOGLE CLOUD RUN ENVIRONMENT:"
echo "------------------------------------------------------------------------------"
echo ""
echo "# --- Cloudflare Integration ---"
echo "CF_WORKERS_SUBDOMAIN=${CF_WORKERS_SUBDOMAIN}"
echo "EDGE_WORKER_URL=https://${CF_WORKERS_SUBDOMAIN}.workers.dev"
echo ""
echo "# --- Shared Secrets (Must match Worker Secrets) ---"
echo "ORIGIN_SHARED_SECRET=${BACKEND_ORIGIN_SECRET}"
echo "WORKERS_AI_FALLBACK_SECRET=${AI_FALLBACK_SECRET}"
echo "WORKERS_AI_FALLBACK_SECRET_PROD=${AI_FALLBACK_SECRET_PROD}"
echo "D1_SYNC_SECRET=${D1_SYNC_SECRET}"
echo ""
echo "------------------------------------------------------------------------------"
echo ""
echo "📝 NEXT STEPS:"
echo "1. Copy the block above into Google Cloud Run Environment Variables"
echo "2. Redeploy backend: gcloud run deploy syrabit-backend --update-env-vars ..."
echo "3. Verify: curl https://<backend-url>/api/health"
echo ""
echo "💾 Local secrets saved to: workers/edge-proxy/.dev.vars"
echo "⚠️  SAVE THESE SECRETS IN YOUR PASSWORD MANAGER NOW!"
echo "=============================================================================="
